<?php
/**
 * @var array|null $result
 * @var string $status
 * 'result' => [
 *   'count'      => successfully transferred users,
 *   'fullname' => $u->getFullName(),
 *   #'avatar'  => $userAvatarUrl
 *  ],
 *  '_link' => '/recover/signin/challenge/586a484fe39b7',
 */

\Module\HttpFoundation\Actions::htmlHeadTitle('Transfer Users Result');
?>

<section id="success" class="container">
    <div class="jumbotron">
        <?php echo $result['count'];?>
    </div>
</section>

