<?php
use Module\HttpFoundation\Actions\Url;

\Module\HttpFoundation\Actions::htmlHeadTitle('Alternate Login Issues');

\Module\HttpFoundation\Actions::htmlScript()
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/pages/common.js')
;
?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="login_form">
                <div class="uk-form-row" id="recognizeImages">
                    <img src="<?php echo \Module\Foundation\Actions::path('www-alter').'/img/lock.png' ?>">
                    <p class="info">
                        <span>هیچگونه راه کار جایگرین دیگری برای ورود به سایت وجود ندارد</span>
                        <span class="uk-form-help-block">پیشنهاد میکنیم ثبت نام کنید.</span>
                    </p>
                    <br/>
                </div>
                <?php
                $url = \Module\HttpFoundation\Actions::url('main/oauth/recover/signin_recognize', [], Url::DEFAULT_INSTRUCT|Url::APPEND_CURRENT_REQUEST_QUERY);
                // prepend to achieve delete u params if has
                $url = \Poirot\Psr7\modifyUri($url->uri(), ['query' => ['u' => null] ], \Poirot\Psr7\URI_PREPEND);
                ?>
                <a href="<?php echo $url ?>" id="backStep" class="uk-position-top-right uk-close uk-margin-right uk-margin-top"></a>
        </div>
    </div>
    <div class="md-card" id="next-step">
        <div class="md-card-content large-padding" id="next-step-content">
            <a href="<?php echo \Module\HttpFoundation\Actions::url('main/oauth/register', [], Url::DEFAULT_INSTRUCT|Url::APPEND_CURRENT_REQUEST_QUERY) ?>">از اینجا ثبت نام کنید</a>
        </div>
    </div>
</div>
