<meta charset="UTF-8"/>
<meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="msapplication-tap-highlight" content="no"/>

<?php echo \Module\HttpFoundation\Actions::htmlHeadTitle('Account Server') ?>

<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/fonts/IranSans/iransans.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/kendo.common-material.min.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/kendo.material.min.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/kendo.rtl.min.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/uikit.rtl.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/login_page.min.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/pages/register.css"/>
<link rel="stylesheet" media="all" href="<?php echo \Module\Foundation\Actions::path('www-alter') ?>/css/toastr.css"/>


<?php // Head Scripts Attached From Head Section
echo \Module\HttpFoundation\Actions::htmlScript('head')
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/common.min.js')
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/toastr.js')
;
