<?php
/**
 * @var \Module\Foundation\ServiceManager\ViewModelRenderer $this
 * @var \Exception $exception
 */

/** @var \Poirot\OAuth2\Server\Exception\exOAuthServer $exception */
$exception = $exception->getPrevious();
?>
<section id="error" class="container">
    <h1>OAuth Server Error !!</h1>
    <h4><?php echo $exception->getError()->getErrorDescription(); ?></h4>
    <p><?php echo $exception->getError()->getHint(); ?></p>
    <p><?php echo $exception->getError()->getErrorUri(); ?></p>
</section>
