<?php
use Module\OAuth2\Actions\Recover\SigninNewPassPage;

\Module\HttpFoundation\Actions::htmlHeadTitle('Pick New Password');

\Module\HttpFoundation\Actions::htmlScript()
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/pages/common.js')
;

if (\Module\HttpFoundation\Actions::flashMessage(SigninNewPassPage::FLASH_MESSAGE_ID)->hasMessages())
    echo \Module\Foundation\Actions::view( 'partial/flashMessage', \Module\HttpFoundation\Actions::flashMessage(SigninNewPassPage::FLASH_MESSAGE_ID)->fetchMessages() );

?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="register_form">
            <form action="<?php echo \Module\HttpFoundation\Actions::url(null, null, true) ?>" method="post" novalidate>
                <div class="uk-form-row">
                    <div class="parsley-row uk-form-password">
                        <label for="identifier">گذرواژه جدید انتخاب کنید</label>
                        <br/>
                        <input class="md-input font-is" type="password" id="password" name="newpassword" placeholder="اینجا کلیک و تایپ کنید ..." autocomplete="off" required/>
                        <a href="" class="uk-form-password-toggle" data-uk-form-password="{lblShow:'نمایش', lblHide:'پنهان'}">نمایش</a>
                        <span class="uk-form-help-block">کلمه عبور را به خاطر بسپارید، برای مراجعت های بعدی به سایت به آن نیاز دارید.</span>
                    </div>
                </div>
                <div class="uk-margin-medium-top">
                    <button type="submit" class="md-btn md-btn-primary md-btn-block md-btn-large font-is">ثبت شود</button>
                </div>

            </form>
        </div>

    </div>
    <div class="uk-margin-top uk-text-center">
        <a href="<?php echo \Module\HttpFoundation\Actions::url(null, null, true)->uri()->withQuery('skip=') ?>">باشه برای بعد ...</a>
    </div>
</div>
