<?php
use Module\HttpFoundation\Actions\Url;
use Module\OAuth2\Actions\User\LoginPage;

\Module\HttpFoundation\Actions::htmlHeadTitle('Login To Continue');

\Module\HttpFoundation\Actions::htmlScript()
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/pages/login.js')
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/pages/common.js')
;

if (\Module\HttpFoundation\Actions::flashMessage(LoginPage::FLASH_MESSAGE_ID)->hasMessages())
    echo \Module\Foundation\Actions::view( 'partial/flashMessage', \Module\HttpFoundation\Actions::flashMessage(LoginPage::FLASH_MESSAGE_ID)->fetchMessages() );

?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="login_form">
            <form action="<?php echo \Module\HttpFoundation\Actions::url(null, [], Url::DEFAULT_INSTRUCT|Url::APPEND_CURRENT_REQUEST_QUERY) ?>" method="post" novalidate>
                <div class="uk-form-row">
                    <div class="parsley-row">
                        <label for="login_username">نام کاربری</label>
                        <input class="md-input font-is" type="text" id="login_username" name="username" minlength="5" maxlength="32" required/>
                    </div>
                </div>
                <div class="uk-form-row">
                    <div class="parsley-row">
                        <label for="login_password">کلمه عبور</label>
                        <input class="md-input font-is" type="password" id="login_password" name="password" minlength="6" maxlength="32" autocomplete="off"  required/>
                    </div>
                </div>
                <div class="uk-margin-medium-top">
                    <button type="submit" class="md-btn md-btn-primary md-btn-block md-btn-large font-is">ورود</button>
                </div>
                <div class="uk-margin-top uk-margin-bottom">
                    <br/>
                    <a href="<?php echo \Module\HttpFoundation\Actions::url('main/oauth/recover/signin_recognize', [], Url::DEFAULT_INSTRUCT|Url::APPEND_CURRENT_REQUEST_QUERY); ?>" class="uk-float-right font-size-small">نمیتوانم وارد شوم، دیگر راههای ورود!</a>
                    <!--<span class="icheck-inline uk-margin-remove">
                            <input type="checkbox" name="login_page_stay_signed" id="login_page_stay_signed" data-md-icheck />
                            <label for="login_page_stay_signed" class="inline-label font-size-small">مرا به خاطر بسپار</label>
                        </span>-->
                </div>
            </form>
        </div>

    </div>
    <div class="uk-margin-top uk-text-center">
        <a href="<?php echo \Module\HttpFoundation\Actions::url('main/oauth/register', [], Url::DEFAULT_INSTRUCT|Url::APPEND_CURRENT_REQUEST_QUERY) ?>">ثبت نام</a>
    </div>
</div>
