<?php
/**
 * @var array                                         $user
 */
use Module\HttpFoundation\Actions\Url;

\Module\HttpFoundation\Actions::htmlHeadTitle('Alternate Login Issues');

\Module\HttpFoundation\Actions::htmlScript()
    ->attachFile(\Module\Foundation\Actions::path('www-alter').'/js/pages/common.js')
;
?>
<div class="login_page_wrapper">
    <div class="md-card" id="login_card">
        <div class="md-card-content large-padding" id="login_form">
                <div class="uk-form-row" id="recognizeImages">
                    <img src="<?php echo \Module\Foundation\Actions::path('www-alter').'/img/user.png' ?>">
                    <p>کاربر گرامی، خوش آمدید ....</p>
                </div>
                <?php
                    $url = \Module\HttpFoundation\Actions::url('main/oauth/logout', [], Url::DEFAULT_INSTRUCT|Url::APPEND_CURRENT_REQUEST_QUERY);
                ?>
                <a href="<?php echo $url ?>" id="backStep" class="uk-position-top-right uk-close uk-margin-right uk-margin-top"></a>
        </div>

    </div>
</div>
